

export const defaultTheme ={
    Cores:{
        backgroundMessage: '#D4D4D4',
        balloonMessageReceived: '#ffffff',
        text: "#111B21",
        balloonMessageSend: "#D9FDD3",
        IconMissedCall: "#EA0038",
        footerBacgroundMessage:"#F0F2F5",
        Icon: "#444444",
        messageFild: '#FFFFFF',
        header: "#F0F2F5",
        colorNotification: "green",
        backgroundListUser: "#FFFFFF",
        backgroundWhatsApp: "#d2dbdc",
        icon: "#919191",
        searchBackground: "#f6f6f6",
        searchBackgroundBOrderBotton: "#EEE",
        BottonBorderMessage: "#EEE",
        searchBackgroundInput: "#FFF",
        DataColor: "#999",
        BackgroundMessageList: "#FFF",
        ListUserHover: "#f5f5f5",
        BackgroundSidebar: "#EDEDED",
        ColorScroBar: 'rgba(0,0,0,0.2)',
        backgroundIntrod: "#f8f9fa",
        BarrabottomIntrod: "#4adf83",
        ColorIntrodH1: "#525252",
        ColorIntrodH2: "#777",
        UserActiveListMessage: "#ebebeb",
        colorChatWindowsHeaderBorder: "#ccc",
        ColorBackgroundWindowsBody: "#e5ddd5",  
        ColorFillMessage: "#FFF",
        ColorFillMessageText: "#4a4a4a",
        colorEmojiOpen: '#009688',
        BallMessage: "#FFF",
        BallMessageShadon: '#ccc',
        backgroundColorBallonRecive: '#fff',
        backgroundColorBallonSend: '#dcf8c6',
        BackgroundColorNewChat: "#fff",
        BackgroundNewChatHead: '#00bfa5',
        BorderNewChat: '#ddd',
        IconNewChat: '#fff',
        ColorNewChatMessage: '#fff',
        ColorButtomLogin: '#4adf83',
        BackgroundLogin: '#D4D4D4',

    }
}           